server:
  port: 9003
  servlet:
    context-path: /tally

jdbc:
  url: jdbc:mysql://47.106.100.193:39517/tally?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
  username: root
  password: jun2018@)!*
  driver: com.mysql.cj.jdbc.Driver

rsa:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCiPu8VpggQt3zlQV0P4clOuI34C6FhEuZAiC8b3Y4Oq3Umx+m0JoemJ0s/bd4nxVMUru02XWYEEkCumo0OBX6kHj0aA3G3NvKN19nZDJj+AUpu8sRAiJh/EOlrYC1qiBq7TfbUpBxnb24cOq4fwdAvng+O+lccICK712FAYCnILQIDAQAB
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKI+7xWmCBC3fOVBXQ/hyU64jfgLoWES5kCILxvdjg6rdSbH6bQmh6YnSz9t3ifFUxSu7TZdZgQSQK6ajQ4FfqQePRoDcbc28o3X2dkMmP4BSm7yxECImH8Q6WtgLWqIGrtN9tSkHGdvbhw6rh/B0C+eD476VxwgIrvXYUBgKcgtAgMBAAECgYEAhNe6sqMLH4TdQmjOZd6dEVOTCnGbZPwwgs3+pHY3hlNkzKgK9nJFxwmNVxYCO9YZPGot18GJcfPv+gaZT8237iLhhpmz73XJRjipraukfxCe0C9edJFrsswRMuFonpr972Wwby+bnhteHmO4be33NNECb9AgTTW+ZoBVkNXZ5YECQQDR6vzpYu3FuZl6f3j29AIkiTcN1IeAbxahN38aRI8azyO0sQquvh7D+JZmOPCcgOLq7BQd3MyG5wE7f2Ue7KwpAkEAxdzcJYO944be8bSle8k6lUxx5YPxD30HdQAI//QKLrM4n7RVTZ1E4Ic0VhNuvQPerz/Lm9e8SUbkMnKdivZ8ZQJBAKRvR+hmR01wgspTWmVQZPFLzyV1SyOPYZGuEFF6TQM6KYUcffq+EQmADAhNKCXgTGCrx2JRGKHACNYbiBG+YWkCQF8Kj9SVS4kXJ9ACbdrf9fvxFGSi1BAUhph0w93uY1W7UN+lx7PYb1VKnKEcBH1WdojHpA3futmX69UvqO0vKOECQBwMJf9QPF7UdvPnlah5yaxWJbWNM8tR2OarQ64KfTnV7vwfOaTMzsINeoWhInB9AtCwyELzXAFym7ir0LKEOMo=

spring:
  redis:
    host: 47.106.100.193
    port: 6333
    password: 6a28b9d3c34d47ccb2750d85544a9487